version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_name: "com.github.librepdf:openpdf"
